"""empty message

Revision ID: 12ebf9dfefd3
Revises: 2273f2c6d4ef
Create Date: 2022-03-26 17:03:17.642213

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '12ebf9dfefd3'
down_revision = '2273f2c6d4ef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
