"""empty message

Revision ID: 2273f2c6d4ef
Revises: 
Create Date: 2022-03-26 16:56:32.487133

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2273f2c6d4ef'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
