"""empty message

Revision ID: 89444ac241c3
Revises: 
Create Date: 2022-03-26 20:56:15.812739

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '89444ac241c3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('schools',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('dbn', sa.String(length=100), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('year', sa.String(length=100), nullable=True),
    sa.Column('total_enrollment', sa.String(length=10), nullable=True),
    sa.Column('grade_k_number', sa.String(length=50), nullable=True),
    sa.Column('grade_1_number', sa.String(length=50), nullable=True),
    sa.Column('grade_2_number', sa.String(length=50), nullable=True),
    sa.Column('grade_3_number', sa.String(length=50), nullable=True),
    sa.Column('grade_4_number', sa.String(length=50), nullable=True),
    sa.Column('grade_5_number', sa.String(length=50), nullable=True),
    sa.Column('grade_6_number', sa.String(length=50), nullable=True),
    sa.Column('grade_7_number', sa.String(length=50), nullable=True),
    sa.Column('grade_8_number', sa.String(length=50), nullable=True),
    sa.Column('female_number', sa.String(length=50), nullable=True),
    sa.Column('female_percentage', sa.String(length=50), nullable=True),
    sa.Column('male_number', sa.String(length=50), nullable=True),
    sa.Column('male_percentage', sa.String(length=50), nullable=True),
    sa.Column('black_number', sa.String(length=50), nullable=True),
    sa.Column('black_percentage', sa.String(length=50), nullable=True),
    sa.Column('asian_number', sa.String(length=50), nullable=True),
    sa.Column('asian_percentage', sa.String(length=50), nullable=True),
    sa.Column('hispanic_number', sa.String(length=50), nullable=True),
    sa.Column('hispanic_percentage', sa.String(length=50), nullable=True),
    sa.Column('other_number', sa.String(length=50), nullable=True),
    sa.Column('other_percentage', sa.String(length=50), nullable=True),
    sa.Column('white_number', sa.String(length=50), nullable=True),
    sa.Column('white_percentage', sa.String(length=50), nullable=True),
    sa.Column('spanish_number', sa.String(length=50), nullable=True),
    sa.Column('spanish_percentage', sa.String(length=50), nullable=True),
    sa.Column('chinese_number', sa.String(length=50), nullable=True),
    sa.Column('chinese_percentage', sa.String(length=50), nullable=True),
    sa.Column('bengali_number', sa.String(length=50), nullable=True),
    sa.Column('bengali_percentage', sa.String(length=50), nullable=True),
    sa.Column('arabic_number', sa.String(length=50), nullable=True),
    sa.Column('arabic_percentage', sa.String(length=50), nullable=True),
    sa.Column('haitian_number', sa.String(length=50), nullable=True),
    sa.Column('haitian_percentage', sa.String(length=50), nullable=True),
    sa.Column('french_number', sa.String(length=50), nullable=True),
    sa.Column('french_percentage', sa.String(length=50), nullable=True),
    sa.Column('russian_number', sa.String(length=50), nullable=True),
    sa.Column('russian_percentage', sa.String(length=50), nullable=True),
    sa.Column('korean_number', sa.String(length=50), nullable=True),
    sa.Column('korean_percentage', sa.String(length=50), nullable=True),
    sa.Column('urdu_number', sa.String(length=50), nullable=True),
    sa.Column('urdu_percentage', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('schools')
    # ### end Alembic commands ###
