"""empty message

Revision ID: b5cf3ba60a84
Revises: 12ebf9dfefd3
Create Date: 2022-03-26 17:15:18.670036

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b5cf3ba60a84'
down_revision = '12ebf9dfefd3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('schools',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('dbn', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('year', sa.String(), nullable=True),
    sa.Column('total_enrollment', sa.Integer(), nullable=True),
    sa.Column('grade_k_number', sa.Integer(), nullable=True),
    sa.Column('grade_1_number', sa.Integer(), nullable=True),
    sa.Column('grade_2_number', sa.Integer(), nullable=True),
    sa.Column('grade_3_number', sa.Integer(), nullable=True),
    sa.Column('grade_4_number', sa.Integer(), nullable=True),
    sa.Column('grade_5_number', sa.Integer(), nullable=True),
    sa.Column('grade_6_number', sa.Integer(), nullable=True),
    sa.Column('grade_7_number', sa.Integer(), nullable=True),
    sa.Column('grade_8_number', sa.Integer(), nullable=True),
    sa.Column('female_number', sa.Integer(), nullable=True),
    sa.Column('female_percentage', sa.Float(), nullable=True),
    sa.Column('male_number', sa.Integer(), nullable=True),
    sa.Column('male_percentage', sa.Float(), nullable=True),
    sa.Column('black_number', sa.Integer(), nullable=True),
    sa.Column('black_percentage', sa.Float(), nullable=True),
    sa.Column('asian_number', sa.Integer(), nullable=True),
    sa.Column('asian_percentage', sa.Float(), nullable=True),
    sa.Column('hispanic_number', sa.Integer(), nullable=True),
    sa.Column('hispanic_percentage', sa.Float(), nullable=True),
    sa.Column('other_number', sa.Integer(), nullable=True),
    sa.Column('other_percentage', sa.Float(), nullable=True),
    sa.Column('white_number', sa.Integer(), nullable=True),
    sa.Column('white_percentage', sa.Float(), nullable=True),
    sa.Column('spanish_number', sa.Integer(), nullable=True),
    sa.Column('spanish_percentage', sa.Float(), nullable=True),
    sa.Column('chinese_number', sa.Integer(), nullable=True),
    sa.Column('chinese_percentage', sa.Float(), nullable=True),
    sa.Column('bengali_number', sa.Integer(), nullable=True),
    sa.Column('bengali_percentage', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('schools')
    # ### end Alembic commands ###
