from app.database import Base
from sqlalchemy import Column,Integer,String, Float


class School(Base):
    __tablename__ = 'schools'
    id = Column(Integer, primary_key=True, autoincrement=True)
    dbn = Column(String(100))
    name = Column(String(100))
    category = Column(String(100))
    year = Column(String(100))
    total_enrollment = Column(String(10), nullable=True)
    grade_k_number = Column(String(50), nullable=True)
    grade_1_number = Column(String(50), nullable=True)
    grade_2_number = Column(String(50), nullable=True)
    grade_3_number = Column(String(50), nullable=True)
    grade_4_number = Column(String(50), nullable=True)
    grade_5_number = Column(String(50), nullable=True)
    grade_6_number = Column(String(50), nullable=True)
    grade_7_number = Column(String(50), nullable=True)
    grade_8_number = Column(String(50), nullable=True)
    female_number = Column(String(50), nullable=True)
    female_percentage = Column(String(50), nullable=True)
    male_number = Column(String(50), nullable=True)
    male_percentage = Column(String(50), nullable=True)
    black_number = Column(String(50), nullable=True)
    black_percentage = Column(String(50), nullable=True)
    asian_number = Column(String(50), nullable=True)
    asian_percentage = Column(String(50), nullable=True)
    hispanic_number = Column(String(50), nullable=True)
    hispanic_percentage = Column(String(50), nullable=True)
    other_number = Column(String(50), nullable=True)
    other_percentage = Column(String(50), nullable=True)
    white_number = Column(String(50), nullable=True)
    white_percentage = Column(String(50), nullable=True)
    spanish_number = Column(String(50), nullable=True)
    spanish_percentage = Column(String(50), nullable=True)
    chinese_number = Column(String(50), nullable=True)
    chinese_percentage = Column(String(50), nullable=True)
    bengali_number = Column(String(50), nullable=True)
    bengali_percentage = Column(String(50), nullable=True)
    arabic_number = Column(String(50), nullable=True)
    arabic_percentage = Column(String(50), nullable=True)
    haitian_number = Column(String(50), nullable=True)
    haitian_percentage = Column(String(50), nullable=True)
    french_number = Column(String(50), nullable=True)
    french_percentage = Column(String(50), nullable=True)
    russian_number = Column(String(50), nullable=True)
    russian_percentage = Column(String(50), nullable=True)
    korean_number = Column(String(50), nullable=True)
    korean_percentage = Column(String(50), nullable=True)
    urdu_number = Column(String(50), nullable=True)
    urdu_percentage = Column(String(50), nullable=True)




